### ISSUE TITLE
Euclidian distance in lab01_distance_matrix

### ISSUE THREAD

**Issue by mpjan** [joaopfonseca/Data-Mining-21-22#1]
In the cell with the 2 for loops, `single_dist` is defined as `sum((data[i] - data[j]) ** 2) ** 1/2`. But shouldn't there be parentheses around the `1/2`? Such that:

```python
single_dist = sum((data[i] - data[j]) ** 2) ** (1/2)
```

The answer changes depending on that.

**Comment by joaopfonseca** [comment]
Thank you for pointing that out! You are correct, it should be fixed now.
